### ISSUE TITLE
Disabled container path issue

### ISSUE THREAD

**Issue by Halyul** [EideardVMR/unraid-easybackup#9]
Hi, I have two containers (`nextcloud` and `caddy` for php-fastcgi reason) share the same path (e.g. `/mnt/user/appdata/nextcloud`), so I disabled the nextcloud path in `caddy`. However, the same path in `nextcloud` is also disabled, causing the path not being backed up. 

I can only backup the nextcloud path when I disable the backup for the whole `caddy` container, but not excluding the nextcloud path only.

A sample `docker-compose.yaml`
```yaml
services:
  caddy:
    build: ./caddy
    volumes:
      - <any other voulmes for data>
      - /mnt/user/appdata/nextcloud:/var/www/html
    restart: unless-stopped
    
  nextcloud:
    image: nextcloud:fpm-alpine
    volumes:
      - /mnt/user/appdata/nextcloud:/var/www/html
    restart: unless-stopped
  
  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /mnt/user/appdata/nextcloud:/var/www/html:z
```
